---
title: "Gov 50 Final Project"
author: "Molly Hamlin"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(infer)

hev <- read_csv('HEV_article_2018.csv')

hev
```

```{r}
hev2 <- hev |>
  drop_na() |>
  mutate(electric_car = if_else(buy_electric == "1", "Own electric", "Do not own electric"),
         college = case_when(
    Education_level <= 3 ~ "No college",
    Education_level == 4 ~ "College"))

```

```{r}
age_vars <- hev2 |>
  mutate(
  age_group = case_when (
    Age <= 25 ~ "25 and under",
    Age >= 26 & Age <= 30 ~ "26 - 30",
     Age >= 31 & Age <= 35 ~ "31 - 35",
     Age >= 36 & Age <= 40 ~ "36 - 40",
     Age >= 41 & Age <= 45 ~ "41 - 45",
     Age >= 46 & Age <= 50 ~ "46 - 50",
     Age >= 51 & Age <= 55 ~ "51 - 55",
     Age >= 56 & Age <= 60 ~ "56 - 60",
     Age >= 61 & Age <= 65 ~ "61 - 65",
     Age >= 65 & Age <= 70 ~ "65 - 70",
     Age >= 71 ~ "over 70"),
  electric_car = if_else(buy_electric == "1", "Own electric", "Do not own electric")
  ) |>
  group_by(age_group, electric_car) |>
  summarize(count = n())

age_vars

age_plot <- ggplot(data = age_vars,
                   mapping = aes(x = count,
                       y = age_group, 
                       fill = electric_car)) +
  geom_col(position = "dodge")+
  scale_fill_manual(values = c("Own electric" = "red",
                               "Do not own electric" = "blue"))

age_plot

```


```{r}
age_ate <- hev2 |>
  mutate(age_two_groups = case_when(
    Age <= 40 ~ "40 and under",
    Age >= 41 ~ "41 and over")) |>
  group_by(age_two_groups) |>
  summarize(mean_buy_electric = mean(buy_electric)) |>
  pivot_wider(names_from = age_two_groups,
              values_from = mean_buy_electric) |>
  mutate(ATE = `40 and under` - `41 and over`) |>
  summarize(ATE)

knitr::kable(age_ate)
```

```{r}
college_vars <- hev2 |>
   mutate(college = case_when(
    Education_level <= 3 ~ "No college",
    Education_level == 4 ~ "College"),
    electric_car = if_else(buy_electric == "1", "Own electric", "Do not own electric"))|>
  group_by(college, electric_car) |>
  summarize(count = n())

college_plot <- ggplot(data = college_vars,
                   mapping = aes(x = college,
                       y = count,
                       fill = electric_car)) +
  geom_col(position = "dodge")+
  scale_fill_manual(values = c("Own electric" = "red",
                               "Do not own electric" = "blue"))

college_plot

```


```{r}
college_ate <- hev2 |>
  filter(Employment_status == "1") |>
  mutate(college = case_when(
    Education_level <= 3 ~ "No college",
    Education_level == 4 ~ "College")) |>
  group_by(college) |>
  summarize(mean_buy_electric = mean(buy_electric)) |>
  pivot_wider(names_from = college,
              values_from = mean_buy_electric) |>
  mutate(ATE = `College` - `No college`) |>
  summarize(ATE)
  

knitr::kable(college_ate)
```

filtered employment status^^^

```{r}
hev2 <- hev2 |>
  mutate(college_num = case_when(
    Education_level == 3 ~ "0",
    Education_level == 4 ~ "1"
  ))

```

```{r}

lm_hev_ed <- lm(buy_electric ~ college_num, data = hev2)


modelsummary::modelsummary(lm_hev_ed,
                           statistic = c("s.e. = {std.error}",
                                         "p = {p.value}"),
                           gof_map = c("nobs", "r.squared", "adj.r.squared"))

```




```{r}
## copied from final exam

lm_hev <- lm(buy_electric ~ Age + college_num + Income_group, data = hev2)


modelsummary::modelsummary(lm_hev,
                           statistic = c("s.e. = {std.error}",
                                         "p = {p.value}"),
                           gof_map = c("nobs", "r.squared", "adj.r.squared"))


```

income group, 1 = high income, 5 = low income



